namespace HomeBook.Backend.Abstractions.Setup;

public enum EnvironmentVariables
{
    DATABASE_TYPE,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_NAME,
    DATABASE_USER,
    DATABASE_PASSWORD,
    HOMEBOOK_ACCEPT_LICENSES,
    HOMEBOOK_USER_NAME,
    HOMEBOOK_USER_PASSWORD,
    HOMEBOOK_INSTANCE_NAME
}
