//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBook.Frontend.Module.Kitchen.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HomeBook.Frontend.Module.Kitchen.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Recipes_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_Recipes_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Pantry_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_Pantry_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Recipes_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_Recipes_Caption", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Pantry_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_Pantry_Caption", resourceCulture);
            }
        }
        
        public static string StartMenuItem_MealPlan_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_MealPlan_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_MealPlan_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_MealPlan_Caption", resourceCulture);
            }
        }
        
        public static string DateTimeFormat_ShortDateOnlyFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat_ShortDateOnlyFormat", resourceCulture);
            }
        }
        
        public static string PlanOverview_Header_CalendarWeek_TextTemplate {
            get {
                return ResourceManager.GetString("PlanOverview_Header_CalendarWeek_TextTemplate", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Breakfast_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Breakfast_Text", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Lunch_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Lunch_Text", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Dinner_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Dinner_Text", resourceCulture);
            }
        }
        
        public static string RecipeOverview_AnnotationServings_TextTemplate {
            get {
                return ResourceManager.GetString("RecipeOverview_AnnotationServings_TextTemplate", resourceCulture);
            }
        }
    }
}
