// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Finances.SavingGoals.Item.Amounts;
using HomeBook.Client.Finances.SavingGoals.Item.Appearance;
using HomeBook.Client.Finances.SavingGoals.Item.Info;
using HomeBook.Client.Finances.SavingGoals.Item.Name;
using HomeBook.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace HomeBook.Client.Finances.SavingGoals.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \finances\saving-goals\{savingGoalId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSavingGoalItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The amounts property</summary>
        public global::HomeBook.Client.Finances.SavingGoals.Item.Amounts.AmountsRequestBuilder Amounts
        {
            get => new global::HomeBook.Client.Finances.SavingGoals.Item.Amounts.AmountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appearance property</summary>
        public global::HomeBook.Client.Finances.SavingGoals.Item.Appearance.AppearanceRequestBuilder Appearance
        {
            get => new global::HomeBook.Client.Finances.SavingGoals.Item.Appearance.AppearanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::HomeBook.Client.Finances.SavingGoals.Item.Info.InfoRequestBuilder Info
        {
            get => new global::HomeBook.Client.Finances.SavingGoals.Item.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::HomeBook.Client.Finances.SavingGoals.Item.Name.NameRequestBuilder Name
        {
            get => new global::HomeBook.Client.Finances.SavingGoals.Item.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Finances.SavingGoals.Item.WithSavingGoalItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSavingGoalItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/finances/saving-goals/{savingGoalId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Finances.SavingGoals.Item.WithSavingGoalItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSavingGoalItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/finances/saving-goals/{savingGoalId}", rawUrl)
        {
        }
        /// <summary>
        /// deletes an existing finances saving goal for the userHTTP 200: Finances saving goal was deletedHTTP 401: User is not authorizedHTTP 404: Saving goal not foundHTTP 500: Unknown error while deleting saving goal
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(global::HomeBook.Client.Models.CreateSavingGoalRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(global::HomeBook.Client.Models.CreateSavingGoalRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// deletes an existing finances saving goal for the userHTTP 200: Finances saving goal was deletedHTTP 401: User is not authorizedHTTP 404: Saving goal not foundHTTP 500: Unknown error while deleting saving goal
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::HomeBook.Client.Models.CreateSavingGoalRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::HomeBook.Client.Models.CreateSavingGoalRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Finances.SavingGoals.Item.WithSavingGoalItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::HomeBook.Client.Finances.SavingGoals.Item.WithSavingGoalItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::HomeBook.Client.Finances.SavingGoals.Item.WithSavingGoalItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSavingGoalItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
