// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.System.Instance.Info;
using HomeBook.Client.System.Instance.Name;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.System.Instance
{
    /// <summary>
    /// Builds and executes requests for operations under \system\instance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The info property</summary>
        public global::HomeBook.Client.System.Instance.Info.InfoRequestBuilder Info
        {
            get => new global::HomeBook.Client.System.Instance.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::HomeBook.Client.System.Instance.Name.NameRequestBuilder Name
        {
            get => new global::HomeBook.Client.System.Instance.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.System.Instance.InstanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system/instance", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.System.Instance.InstanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system/instance", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
