// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HomeBook.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetDatabaseCheckResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The databaseHost property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseHost { get; set; }
#nullable restore
#else
        public string DatabaseHost { get; set; }
#endif
        /// <summary>The databaseName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseName { get; set; }
#nullable restore
#else
        public string DatabaseName { get; set; }
#endif
        /// <summary>The databasePort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabasePort { get; set; }
#nullable restore
#else
        public string DatabasePort { get; set; }
#endif
        /// <summary>The databaseUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseUserName { get; set; }
#nullable restore
#else
        public string DatabaseUserName { get; set; }
#endif
        /// <summary>The databaseUserPassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatabaseUserPassword { get; set; }
#nullable restore
#else
        public string DatabaseUserPassword { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Models.GetDatabaseCheckResponse"/> and sets the default values.
        /// </summary>
        public GetDatabaseCheckResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.GetDatabaseCheckResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HomeBook.Client.Models.GetDatabaseCheckResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HomeBook.Client.Models.GetDatabaseCheckResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "databaseHost", n => { DatabaseHost = n.GetStringValue(); } },
                { "databaseName", n => { DatabaseName = n.GetStringValue(); } },
                { "databasePort", n => { DatabasePort = n.GetStringValue(); } },
                { "databaseUserName", n => { DatabaseUserName = n.GetStringValue(); } },
                { "databaseUserPassword", n => { DatabaseUserPassword = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("databaseHost", DatabaseHost);
            writer.WriteStringValue("databaseName", DatabaseName);
            writer.WriteStringValue("databasePort", DatabasePort);
            writer.WriteStringValue("databaseUserName", DatabaseUserName);
            writer.WriteStringValue("databaseUserPassword", DatabaseUserPassword);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
