// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HomeBook.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SavingGoalResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The currentAmount property</summary>
        public double? CurrentAmount { get; set; }
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The interestRate property</summary>
        public double? InterestRate { get; set; }
        /// <summary>The interestRateOption property</summary>
        public int? InterestRateOption { get; set; }
        /// <summary>The monthlyPayment property</summary>
        public double? MonthlyPayment { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The targetAmount property</summary>
        public double? TargetAmount { get; set; }
        /// <summary>The targetDate property</summary>
        public DateTimeOffset? TargetDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Models.SavingGoalResponse"/> and sets the default values.
        /// </summary>
        public SavingGoalResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.SavingGoalResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HomeBook.Client.Models.SavingGoalResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HomeBook.Client.Models.SavingGoalResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetStringValue(); } },
                { "currentAmount", n => { CurrentAmount = n.GetDoubleValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "interestRate", n => { InterestRate = n.GetDoubleValue(); } },
                { "interestRateOption", n => { InterestRateOption = n.GetIntValue(); } },
                { "monthlyPayment", n => { MonthlyPayment = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "targetAmount", n => { TargetAmount = n.GetDoubleValue(); } },
                { "targetDate", n => { TargetDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("color", Color);
            writer.WriteDoubleValue("currentAmount", CurrentAmount);
            writer.WriteStringValue("icon", Icon);
            writer.WriteGuidValue("id", Id);
            writer.WriteDoubleValue("interestRate", InterestRate);
            writer.WriteIntValue("interestRateOption", InterestRateOption);
            writer.WriteDoubleValue("monthlyPayment", MonthlyPayment);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("targetAmount", TargetAmount);
            writer.WriteDateTimeOffsetValue("targetDate", TargetDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
