// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HomeBook.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateSavingGoalAmountsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentAmount property</summary>
        public double? CurrentAmount { get; set; }
        /// <summary>The interestRate property</summary>
        public double? InterestRate { get; set; }
        /// <summary>The interestRateOption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption? InterestRateOption { get; set; }
#nullable restore
#else
        public global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption InterestRateOption { get; set; }
#endif
        /// <summary>The monthlyPayment property</summary>
        public double? MonthlyPayment { get; set; }
        /// <summary>The targetAmount property</summary>
        public double? TargetAmount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest"/> and sets the default values.
        /// </summary>
        public UpdateSavingGoalAmountsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentAmount", n => { CurrentAmount = n.GetDoubleValue(); } },
                { "interestRate", n => { InterestRate = n.GetDoubleValue(); } },
                { "interestRateOption", n => { InterestRateOption = n.GetObjectValue<global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption>(global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption.CreateFromDiscriminatorValue); } },
                { "monthlyPayment", n => { MonthlyPayment = n.GetDoubleValue(); } },
                { "targetAmount", n => { TargetAmount = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("currentAmount", CurrentAmount);
            writer.WriteDoubleValue("interestRate", InterestRate);
            writer.WriteObjectValue<global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption>("interestRateOption", InterestRateOption);
            writer.WriteDoubleValue("monthlyPayment", MonthlyPayment);
            writer.WriteDoubleValue("targetAmount", TargetAmount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::HomeBook.Client.Models.InterestRateOptions"/>, <see cref="global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateSavingGoalAmountsRequest_interestRateOption : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::HomeBook.Client.Models.InterestRateOptions"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::HomeBook.Client.Models.InterestRateOptions? InterestRateOptions { get; set; }
#nullable restore
#else
            public global::HomeBook.Client.Models.InterestRateOptions InterestRateOptions { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1? UpdateSavingGoalAmountsRequestInterestRateOptionMember1 { get; set; }
#nullable restore
#else
            public global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1 UpdateSavingGoalAmountsRequestInterestRateOptionMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest.UpdateSavingGoalAmountsRequest_interestRateOption();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InterestRateOptions = new global::HomeBook.Client.Models.InterestRateOptions();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UpdateSavingGoalAmountsRequestInterestRateOptionMember1 = new global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InterestRateOptions != null)
                {
                    return InterestRateOptions.GetFieldDeserializers();
                }
                else if(UpdateSavingGoalAmountsRequestInterestRateOptionMember1 != null)
                {
                    return UpdateSavingGoalAmountsRequestInterestRateOptionMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(InterestRateOptions != null)
                {
                    writer.WriteObjectValue<global::HomeBook.Client.Models.InterestRateOptions>(null, InterestRateOptions);
                }
                else if(UpdateSavingGoalAmountsRequestInterestRateOptionMember1 != null)
                {
                    writer.WriteObjectValue<global::HomeBook.Client.Models.UpdateSavingGoalAmountsRequest_interestRateOptionMember1>(null, UpdateSavingGoalAmountsRequestInterestRateOptionMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
