//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBook.Frontend.Module.Finances.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HomeBook.Frontend.Module.Finances.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Overview_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_Overview_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Overview_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_Overview_Caption", resourceCulture);
            }
        }
        
        public static string Savings_Title {
            get {
                return ResourceManager.GetString("Savings_Title", resourceCulture);
            }
        }
        
        public static string Savings_Add_Title {
            get {
                return ResourceManager.GetString("Savings_Add_Title", resourceCulture);
            }
        }
        
        public static string Savings_Overview_NoSavingGoals {
            get {
                return ResourceManager.GetString("Savings_Overview_NoSavingGoals", resourceCulture);
            }
        }
        
        public static string Savings_Edit_Title {
            get {
                return ResourceManager.GetString("Savings_Edit_Title", resourceCulture);
            }
        }
        
        public static string Savings_Edit_NotFound {
            get {
                return ResourceManager.GetString("Savings_Edit_NotFound", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_Intro_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_Intro_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Intro_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Intro_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_Intro_Description {
            get {
                return ResourceManager.GetString("AddSavingGoal_Intro_Description", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_Intro_QuickAddButton_Text {
            get {
                return ResourceManager.GetString("AddSavingGoal_Intro_QuickAddButton_Text", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Name_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Name_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Plan_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Plan_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Summary_Title {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Summary_Title", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Name_Title_Text {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Name_Title_Text", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Name_Title_Caption {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Name_Title_Caption", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Name_Input_Placeholder {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Name_Input_Placeholder", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_Title_Text {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_Title_Text", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_Title_Caption {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_Title_Caption", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_Input_Placeholder {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_Input_Placeholder", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_Input_ValidationError {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_Input_ValidationError", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_TargetDate_Caption {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_TargetDate_Caption", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_TargetDateInput_Placeholder {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_TargetDateInput_Placeholder", resourceCulture);
            }
        }
        
        public static string AddSavingGoal_MudStep_Goal_TargetDateInput_Label {
            get {
                return ResourceManager.GetString("AddSavingGoal_MudStep_Goal_TargetDateInput_Label", resourceCulture);
            }
        }
    }
}
