// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Platform.Locales;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Platform
{
    /// <summary>
    /// Builds and executes requests for operations under \platform
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlatformRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The locales property</summary>
        public global::HomeBook.Client.Platform.Locales.LocalesRequestBuilder Locales
        {
            get => new global::HomeBook.Client.Platform.Locales.LocalesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Platform.PlatformRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlatformRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/platform", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Platform.PlatformRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlatformRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/platform", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
