// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Setup.Availability;
using HomeBook.Client.Setup.Configuration;
using HomeBook.Client.Setup.Database;
using HomeBook.Client.Setup.Licenses;
using HomeBook.Client.Setup.Start;
using HomeBook.Client.Setup.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Setup
{
    /// <summary>
    /// Builds and executes requests for operations under \setup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The availability property</summary>
        public global::HomeBook.Client.Setup.Availability.AvailabilityRequestBuilder Availability
        {
            get => new global::HomeBook.Client.Setup.Availability.AvailabilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The configuration property</summary>
        public global::HomeBook.Client.Setup.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::HomeBook.Client.Setup.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::HomeBook.Client.Setup.Database.DatabaseRequestBuilder Database
        {
            get => new global::HomeBook.Client.Setup.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenses property</summary>
        public global::HomeBook.Client.Setup.Licenses.LicensesRequestBuilder Licenses
        {
            get => new global::HomeBook.Client.Setup.Licenses.LicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::HomeBook.Client.Setup.Start.StartRequestBuilder Start
        {
            get => new global::HomeBook.Client.Setup.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::HomeBook.Client.Setup.User.UserRequestBuilder User
        {
            get => new global::HomeBook.Client.Setup.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Setup.SetupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Setup.SetupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
