// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Setup.Database.Check;
using HomeBook.Client.Setup.Database.Configuration;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Setup.Database
{
    /// <summary>
    /// Builds and executes requests for operations under \setup\database
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatabaseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check property</summary>
        public global::HomeBook.Client.Setup.Database.Check.CheckRequestBuilder Check
        {
            get => new global::HomeBook.Client.Setup.Database.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The configuration property</summary>
        public global::HomeBook.Client.Setup.Database.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::HomeBook.Client.Setup.Database.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Setup.Database.DatabaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup/database", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Setup.Database.DatabaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatabaseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup/database", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
