// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Kitchen.Recipes;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Kitchen
{
    /// <summary>
    /// Builds and executes requests for operations under \kitchen
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KitchenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The recipes property</summary>
        public global::HomeBook.Client.Kitchen.Recipes.RecipesRequestBuilder Recipes
        {
            get => new global::HomeBook.Client.Kitchen.Recipes.RecipesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Kitchen.KitchenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KitchenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kitchen", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Kitchen.KitchenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KitchenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/kitchen", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
